config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  get 'products/:id', to: 'products#show', as: 'product'
  get 'products', to: 'products#index'

  get 'magic/index'
  get 'magic/search_results'
  get 'magic/:id', to: 'magic#show', as: 'magic'
  get 'magic', to: 'magic#index'

  get 'pages/index'
  get 'pages/about'
  get 'about', to: 'pages#about'

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    # Colors
    has_many :card_colors
    has_many :colors, through: :card_colors

    # Types
    has_many :card_types
    has_many :types, through: :card_types

    # Validations
    validates :Name, presence: true
end

app/models/card_color.rb
class CardColor < ApplicationRecord
  belongs_to :card
  belongs_to :color
end

app/models/card_type.rb
class CardType < ApplicationRecord
  belongs_to :card
  belongs_to :type
end

app/models/color.rb
class Color < ApplicationRecord
    has_many :card_colors
    has_many :cards, through: :card_colors

    validates :Name, presence: true
end

app/models/material.rb
class Material < ApplicationRecord
    has_many :products

    validates :Name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :material

    validates :Name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :card_types
    has_many :cards, through: :card_types

    validates :Name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/magic_controller.rb
class MagicController < ApplicationController
  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def search_results
    @cards = Card.where("name LIKE ?", "%#{params[:q]}%")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/magic_helper.rb
module MagicHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Rails Project</h1>
    <div>
      <%= link_to "Home", root_path %>                                        | 
      <%= link_to "Magic", :controller => :magic, :action => :index %>        | 
      <%= link_to "Products", :controller => :products, :action => :index %>  | 
      <%= link_to "About", :controller => :pages, :action => :about %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/magic/index.html.erb
<h1>Magic The Gathering</h1>

<!-- Search -->
<%= form_tag("search_results", method: "get") do %>
    <%= label_tag(:q, "Search for: ") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
<% end %>

<!-- List -->
<ul>
    <% @cards.each do |card| %>
        <li><%= link_to card.Name, magic_path(card) %></li>
    <% end %>
</ul>

app/views/magic/search_results.erb
<h1>Magic The Gathering</h1>

<% if @cards.empty? %>
    <p>No cards found.</p>
<% else %>
    <p>Found <%= @cards.count %> results.</p>

    <ul>
        <% @cards.each do |card| %>
            <li><%= link_to card.Name, magic_path(card) %></li>
        <% end %>
    </ul>
<% end %>

app/views/magic/show.html.erb
<h1>Magic The Gathering - Card</h1>
<p>Name: <%= @card.Name %></p>
<p>Mana Cost: <%= @card.Manacost %></p>
<p>Colors:
    <ul>
        <% @card.colors.each do |color| %>
            <li>
                <%= color.Name %>
            </li>
        <% end %>
    </ul>
</p>
<p>Type: <%= @card.TypeText %></p>
<p>Types:
    <ul>
        <% @card.types.each do |type| %>
            <li>
                <%= type.Name %>
            </li>
        <% end %>
    </ul>
</p>
<p>Text: <%= @card.Text %></p>
<p>Power: <%= @card.Power %></p>
<p>Toughness: <%= @card.Thoughness %></p>

app/views/pages/about.html.erb
<h1>About</h1>
<p>I`m using Magic The Gathering Data Source, and the Faker Data as the second Data Source.</p>
<br/>
<p>The Magic data is composed of Cards, which have Colors which is another table, and types which is yet another table.</p>
<p>They are connected through many to many relationships(and composite tables).</p>
<br/>
<p>The Faker data has Products, which has a Material foreign key to a Materials Table.</p>

app/views/pages/index.html.erb
<h1>Hello</h1>
<p>This is the index of my super project that contains many Magic the Gathering cards, and also products generated with Faker :D.</p>

app/views/products/index.html.erb
<h1>Products</h1>
<ul>
    <% @products.each do |product| %>
        <li><%= link_to product.Name, product_path(product) %></li>
    <% end %>
</ul>

app/views/products/show.html.erb
<h1>Products - Product</h1>
<p>Name: <%= @product.Name %></p>
<p>Price: <%= @product.Price %></p>
<p>Quantity: <%= @product.Quantity %></p>
<p>Material: <%= @product.material.Name %></p>